// Set-play library. Loaded only after the Set Plays password gate is
// unlocked (see main.js initPlaysGate) — kept out of js/data.js so it
// isn't fetched as part of the normal page load on plays.html/play.html.
// This is a soft deterrent, not real security: this file is still a
// public URL anyone can request directly. See README.md for the
// diagram coordinate format.
const SET_PLAYS = [
  {
    id: "box-elbow-curl",
    name: "Box Elbow Curl",
    category: "Out of Bounds (SLOB)",
    description: "Sideline out-of-bounds set from a box alignment: 3 clears baseline off a screen from 4 as a decoy, while 2 fakes toward the ball outside the three-point line before curling off a back screen from 5 and cutting across the lane to finish on the weak side, away from the traffic on the strong side.",
    keyPoints: [
      "1 inbounds from the sideline.",
      "4 sets a baseline screen for 3, who cuts from the block to the far corner as the decoy/second option.",
      "2 leaves the elbow and cuts toward the ball, staying outside the three-point line, faking like he wants the catch.",
      "5 follows and sets a back screen; 2 curls around it and cuts across the lane to the weak side.",
      "1 hits 2 cutting to the weak-side rim for the score.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: -4, y: 55 },
        { id: "2", label: "2", x: 34, y: 40 },
        { id: "3", label: "3", x: 68, y: 8 },
        { id: "4", label: "4", x: 29, y: 10 },
        { id: "5", label: "5", x: 66, y: 41 },
      ],
      actions: [
        { type: "screen", at: { x: 29, y: 10 }, angle: 90 },
        { type: "cut", path: [{ x: 68, y: 8 }, { x: 38, y: 3 }, { x: 3, y: 3 }] },
        { type: "cut", path: [{ x: 66, y: 41 }, { x: 45, y: 50 }, { x: 20, y: 58 }] },
        { type: "screen", at: { x: 20, y: 58 }, angle: 90 },
        { type: "cut", path: [{ x: 34, y: 40 }, { x: 22, y: 46 }, { x: 14, y: 50 }, { x: 22, y: 68 }, { x: 42, y: 42 }, { x: 62, y: 10 }] },
        { type: "pass", from: { x: -4, y: 55 }, to: { x: 62, y: 10 } },
      ],
    },
    // Step-by-step breakdown for the play detail page. Each step's `players`
    // are positions as of the END of that step (so earlier steps' movement
    // is already reflected), and `actions` are only the arrows that happen
    // during that step, keeping each diagram focused on one beat of the play.
    steps: [
      {
        title: "Initial Alignment",
        narrative: "Box set: 4 and 3 on the blocks, 2 and 5 at the elbows. 1 takes the ball out of bounds on the sideline.",
        players: [
          { id: "1", label: "1", x: -4, y: 55 },
          { id: "2", label: "2", x: 34, y: 40 },
          { id: "3", label: "3", x: 68, y: 8 },
          { id: "4", label: "4", x: 29, y: 10 },
          { id: "5", label: "5", x: 66, y: 41 },
        ],
        actions: [],
      },
      {
        title: "Baseline Screen & Decoy Relocate",
        narrative: "4 sets a baseline screen; 3 cuts off it from the block to the far corner as the decoy. At the same time, 2 leaves the elbow and cuts toward the ball, staying outside the three-point line, faking like he wants the catch.",
        players: [
          { id: "1", label: "1", x: -4, y: 55 },
          { id: "2", label: "2", x: 14, y: 50 },
          { id: "3", label: "3", x: 3, y: 3 },
          { id: "4", label: "4", x: 29, y: 10 },
          { id: "5", label: "5", x: 66, y: 41 },
        ],
        actions: [
          { type: "screen", at: { x: 29, y: 10 }, angle: 90 },
          { type: "cut", path: [{ x: 68, y: 8 }, { x: 38, y: 3 }, { x: 3, y: 3 }] },
          { type: "cut", path: [{ x: 34, y: 40 }, { x: 22, y: 46 }, { x: 14, y: 50 }] },
        ],
      },
      {
        title: "Back Screen",
        narrative: "5 follows behind 2 and sets a back screen just above him, freeing him from the defender chasing the fake catch.",
        players: [
          { id: "1", label: "1", x: -4, y: 55 },
          { id: "2", label: "2", x: 14, y: 50 },
          { id: "3", label: "3", x: 3, y: 3 },
          { id: "4", label: "4", x: 29, y: 10 },
          { id: "5", label: "5", x: 20, y: 58 },
        ],
        actions: [
          { type: "cut", path: [{ x: 66, y: 41 }, { x: 45, y: 50 }, { x: 20, y: 58 }] },
          { type: "screen", at: { x: 20, y: 58 }, angle: 90 },
        ],
      },
      {
        title: "Curl to the Rim",
        narrative: "2 curls off the back screen and cuts hard across the lane to finish on the weak side, away from the crowd the screen and baseline cut left on the strong side.",
        players: [
          { id: "1", label: "1", x: -4, y: 55 },
          { id: "2", label: "2", x: 62, y: 10 },
          { id: "3", label: "3", x: 3, y: 3 },
          { id: "4", label: "4", x: 29, y: 10 },
          { id: "5", label: "5", x: 20, y: 58 },
        ],
        actions: [
          { type: "cut", path: [{ x: 14, y: 50 }, { x: 22, y: 68 }, { x: 42, y: 42 }, { x: 62, y: 10 }] },
        ],
      },
      {
        title: "Inbound Pass & Score",
        narrative: "1 delivers the pass to 2 cutting to the weak-side rim for the finish.",
        players: [
          { id: "1", label: "1", x: -4, y: 55 },
          { id: "2", label: "2", x: 62, y: 10 },
          { id: "3", label: "3", x: 3, y: 3 },
          { id: "4", label: "4", x: 29, y: 10 },
          { id: "5", label: "5", x: 20, y: 58 },
        ],
        actions: [
          { type: "pass", from: { x: -4, y: 55 }, to: { x: 62, y: 10 } },
        ],
      },
    ],
  },
  {
    id: "baseline-post-cross",
    name: "Baseline Post Cross",
    category: "Out of Bounds (BLOB)",
    description: "Baseline out-of-bounds set: 4 comes up to screen for 2 at the free-throw line, then 5 screens the screener — 4 curls off it to arrive slightly on the weak side for the catch and score, while 2 clears to the corner off the first screen.",
    keyPoints: [
      "1 inbounds from under the basket.",
      "4 cuts up from the block to the free-throw line and screens for 2.",
      "2 cuts off the screen toward the baseline, then redirects out to the corner. 3 clears from the right elbow to the top.",
      "5 comes across to screen the screener — 4 curls off it and arrives slightly on the weak side.",
      "1 hits 4 on the weak side for the score. Backup option: instead of screening, 5 can slip straight to the basket from the free-throw line for a quick score.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 9, y: -3 },
        { id: "2", label: "2", x: 29, y: 41 },
        { id: "3", label: "3", x: 67, y: 41 },
        { id: "4", label: "4", x: 29, y: 6 },
        { id: "5", label: "5", x: 72, y: 7 },
      ],
      actions: [
        { type: "cut", path: [{ x: 67, y: 41 }, { x: 61, y: 65 }] },
        { type: "cut", path: [{ x: 29, y: 6 }, { x: 29, y: 36 }] },
        { type: "screen", at: { x: 29, y: 36 }, angle: 0 },
        { type: "cut", path: [{ x: 29, y: 41 }, { x: 27, y: 14 }, { x: -5, y: 24 }] },
        { type: "cut", path: [{ x: 72, y: 7 }, { x: 40, y: 30 }] },
        { type: "screen", at: { x: 40, y: 30 }, angle: 135 },
        { type: "cut", path: [{ x: 29, y: 36 }, { x: 38, y: 32 }, { x: 56, y: 24 }] },
        { type: "pass", from: { x: 9, y: -3 }, to: { x: 56, y: 24 } },
        { type: "cut", path: [{ x: 56, y: 24 }, { x: 52, y: 10 }] },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "Box set on the baseline: 2 and 3 at the elbows, 4 and 5 on the blocks. 1 takes the ball out of bounds under the basket.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: 29, y: 41 },
          { id: "3", label: "3", x: 67, y: 41 },
          { id: "4", label: "4", x: 29, y: 6 },
          { id: "5", label: "5", x: 72, y: 7 },
        ],
        actions: [],
      },
      {
        title: "Screen at the Elbow",
        narrative: "4 cuts up from the block to the free-throw line and sets a screen for 2. 3 begins clearing from the right elbow up to the top.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: 29, y: 41 },
          { id: "3", label: "3", x: 61, y: 65 },
          { id: "4", label: "4", x: 29, y: 36 },
          { id: "5", label: "5", x: 72, y: 7 },
        ],
        actions: [
          { type: "cut", path: [{ x: 29, y: 6 }, { x: 29, y: 36 }] },
          { type: "screen", at: { x: 29, y: 36 }, angle: 0 },
          { type: "cut", path: [{ x: 67, y: 41 }, { x: 61, y: 65 }] },
        ],
      },
      {
        title: "2 Cuts, 5 Screens the Screener",
        narrative: "2 cuts off 4's screen toward the baseline, then redirects out to the corner. At the same time, 5 comes across to set a screen for 4 — the screener.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: -5, y: 24 },
          { id: "3", label: "3", x: 61, y: 65 },
          { id: "4", label: "4", x: 29, y: 36 },
          { id: "5", label: "5", x: 40, y: 30 },
        ],
        actions: [
          { type: "cut", path: [{ x: 29, y: 41 }, { x: 27, y: 14 }, { x: -5, y: 24 }] },
          { type: "cut", path: [{ x: 72, y: 7 }, { x: 40, y: 30 }] },
          { type: "screen", at: { x: 40, y: 30 }, angle: 135 },
        ],
      },
      {
        title: "4 Curls to the Weak Side",
        narrative: "4 curls off 5's screen and pops out slightly on the weak side, looking for the catch.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: -5, y: 24 },
          { id: "3", label: "3", x: 61, y: 65 },
          { id: "4", label: "4", x: 56, y: 24 },
          { id: "5", label: "5", x: 40, y: 30 },
        ],
        actions: [
          { type: "cut", path: [{ x: 29, y: 36 }, { x: 38, y: 32 }, { x: 56, y: 24 }] },
        ],
      },
      {
        title: "Inbound Pass",
        narrative: "1 hits 4, now open slightly on the weak side.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: -5, y: 24 },
          { id: "3", label: "3", x: 61, y: 65 },
          { id: "4", label: "4", x: 56, y: 24 },
          { id: "5", label: "5", x: 40, y: 30 },
        ],
        actions: [
          { type: "pass", from: { x: 9, y: -3 }, to: { x: 56, y: 24 } },
        ],
      },
      {
        title: "Attack & Score",
        narrative: "4 catches in rhythm and attacks the rim for the finish.",
        players: [
          { id: "1", label: "1", x: 9, y: -3 },
          { id: "2", label: "2", x: -5, y: 24 },
          { id: "3", label: "3", x: 61, y: 65 },
          { id: "4", label: "4", x: 52, y: 10 },
          { id: "5", label: "5", x: 40, y: 30 },
        ],
        actions: [
          { type: "cut", path: [{ x: 56, y: 24 }, { x: 52, y: 10 }] },
        ],
      },
    ],
  },
  {
    id: "zone-attack-reversal",
    name: "Zone Attack Reversal",
    category: "Half-Court Offense",
    description: "Half-court entry against a 2-3 zone: a skip pass and ball reversal shift the defense before a baseline cut opens a short-corner score.",
    keyPoints: [
      "1 skip-passes to 3 on the wing, then fills behind it.",
      "3 reverses the ball back to 1 as 4 flashes to the high post.",
      "1 swings it back left as 2 clears to the corner, 3 drifts to the short corner, and 5 seals to the weak-side block.",
      "1 hits 3 in the short corner for the score.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 49, y: 66 },
        { id: "2", label: "2", x: 6, y: 54 },
        { id: "3", label: "3", x: 92, y: 52 },
        { id: "4", label: "4", x: 29, y: 9 },
        { id: "5", label: "5", x: 75, y: 7 },
      ],
      actions: [
        { type: "pass", from: { x: 49, y: 66 }, to: { x: 92, y: 62 } },
        { type: "cut", path: [{ x: 49, y: 66 }, { x: 78, y: 61 }] },
        { type: "pass", from: { x: 92, y: 62 }, to: { x: 78, y: 61 } },
        { type: "cut", path: [{ x: 29, y: 9 }, { x: 63, y: 52 }] },
        { type: "cut", path: [{ x: 78, y: 61 }, { x: 30, y: 49 }] },
        { type: "cut", path: [{ x: 6, y: 54 }, { x: 3, y: 4 }] },
        { type: "cut", path: [{ x: 92, y: 62 }, { x: 66, y: 12 }] },
        { type: "cut", path: [{ x: 75, y: 7 }, { x: 24, y: 4 }] },
        { type: "pass", from: { x: 30, y: 49 }, to: { x: 66, y: 12 } },
        { type: "cut", path: [{ x: 66, y: 12 }, { x: 49, y: 7 }] },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "1-2-2 set against the 2-3 zone: 1 up top with the ball, 2 and 3 on the wings, 4 and 5 on the blocks.",
        players: [
          { id: "1", label: "1", x: 49, y: 66 },
          { id: "2", label: "2", x: 6, y: 54 },
          { id: "3", label: "3", x: 92, y: 52 },
          { id: "4", label: "4", x: 29, y: 9 },
          { id: "5", label: "5", x: 75, y: 7 },
        ],
        actions: [],
      },
      {
        title: "Skip Pass",
        narrative: "1 passes to 3, who lifts along the sideline to meet it above the zone's top defender. 1 fills in behind the pass.",
        players: [
          { id: "1", label: "1", x: 78, y: 61 },
          { id: "2", label: "2", x: 6, y: 54 },
          { id: "3", label: "3", x: 92, y: 62 },
          { id: "4", label: "4", x: 29, y: 9 },
          { id: "5", label: "5", x: 75, y: 7 },
        ],
        actions: [
          { type: "pass", from: { x: 49, y: 66 }, to: { x: 92, y: 62 } },
          { type: "cut", path: [{ x: 49, y: 66 }, { x: 78, y: 61 }] },
        ],
      },
      {
        title: "Reversal & Flash",
        narrative: "3 reverses the ball straight back to 1 as 4 flashes from the block to the high post, drawing the zone's attention to the middle.",
        players: [
          { id: "1", label: "1", x: 78, y: 61 },
          { id: "2", label: "2", x: 6, y: 54 },
          { id: "3", label: "3", x: 92, y: 62 },
          { id: "4", label: "4", x: 63, y: 52 },
          { id: "5", label: "5", x: 75, y: 7 },
        ],
        actions: [
          { type: "pass", from: { x: 92, y: 62 }, to: { x: 78, y: 61 } },
          { type: "cut", path: [{ x: 29, y: 9 }, { x: 63, y: 52 }] },
        ],
      },
      {
        title: "Reversal & Baseline Cuts",
        narrative: "1 dribbles the ball back to the left wing. 2 clears down to the weak-side corner, 3 drifts down into the short corner, and 5 seals across the baseline to the weak-side block.",
        players: [
          { id: "1", label: "1", x: 30, y: 49 },
          { id: "2", label: "2", x: 3, y: 4 },
          { id: "3", label: "3", x: 66, y: 12 },
          { id: "4", label: "4", x: 63, y: 52 },
          { id: "5", label: "5", x: 24, y: 4 },
        ],
        actions: [
          { type: "cut", path: [{ x: 78, y: 61 }, { x: 30, y: 49 }] },
          { type: "cut", path: [{ x: 6, y: 54 }, { x: 3, y: 4 }] },
          { type: "cut", path: [{ x: 92, y: 62 }, { x: 66, y: 12 }] },
          { type: "cut", path: [{ x: 75, y: 7 }, { x: 24, y: 4 }] },
        ],
      },
      {
        title: "Short Corner Score",
        narrative: "1 hits 3 in the short corner; 3 attacks the middle and finishes at the rim.",
        players: [
          { id: "1", label: "1", x: 30, y: 49 },
          { id: "2", label: "2", x: 3, y: 4 },
          { id: "3", label: "3", x: 49, y: 7 },
          { id: "4", label: "4", x: 63, y: 52 },
          { id: "5", label: "5", x: 24, y: 4 },
        ],
        actions: [
          { type: "pass", from: { x: 30, y: 49 }, to: { x: 66, y: 12 } },
          { type: "cut", path: [{ x: 66, y: 12 }, { x: 49, y: 7 }] },
        ],
      },
    ],
  },
  {
    id: "zoom-entry",
    name: "Zoom Entry",
    category: "Half-Court Offense",
    description: "Wing entry and ball reversal: a long cut across the baseline and up the opposite sideline springs a cutter for a catch in stride and a downhill drive.",
    keyPoints: [
      "1 dribbles toward the strong-side corner as 3 lifts up to the wing.",
      "1 enters the ball to 3; 2 drops down to fill the weak-side corner.",
      "4 makes a long cut from the corner, up the sideline and across the top, as 5 lifts to space the middle.",
      "3 hits 4 in stride at the top of the key; 4 attacks downhill and finishes at the rim.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 78, y: 59 },
        { id: "2", label: "2", x: 22, y: 62 },
        { id: "3", label: "3", x: 96, y: 4 },
        { id: "4", label: "4", x: 4, y: 5 },
        { id: "5", label: "5", x: 27, y: 10 },
      ],
      actions: [
        { type: "cut", path: [{ x: 78, y: 59 }, { x: 97, y: 28 }] },
        { type: "cut", path: [{ x: 96, y: 4 }, { x: 92, y: 30 }] },
        { type: "pass", from: { x: 97, y: 28 }, to: { x: 92, y: 30 } },
        { type: "cut", path: [{ x: 22, y: 62 }, { x: 3, y: 9 }] },
        { type: "cut", path: [{ x: 4, y: 5 }, { x: 10, y: 45 }, { x: 37, y: 57 }] },
        { type: "cut", path: [{ x: 27, y: 10 }, { x: 39, y: 47 }] },
        { type: "pass", from: { x: 92, y: 30 }, to: { x: 37, y: 57 } },
        { type: "cut", path: [{ x: 37, y: 57 }, { x: 51, y: 9 }] },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "1 on the right wing with the ball, 2 on the opposite wing, 3 and 4 deep in the corners, 5 at the left block.",
        players: [
          { id: "1", label: "1", x: 78, y: 59 },
          { id: "2", label: "2", x: 22, y: 62 },
          { id: "3", label: "3", x: 96, y: 4 },
          { id: "4", label: "4", x: 4, y: 5 },
          { id: "5", label: "5", x: 27, y: 10 },
        ],
        actions: [],
      },
      {
        title: "Dribble & Lift",
        narrative: "1 dribbles toward the strong-side corner as 3 lifts up the sideline to meet the ball on the wing.",
        players: [
          { id: "1", label: "1", x: 97, y: 28 },
          { id: "2", label: "2", x: 22, y: 62 },
          { id: "3", label: "3", x: 92, y: 30 },
          { id: "4", label: "4", x: 4, y: 5 },
          { id: "5", label: "5", x: 27, y: 10 },
        ],
        actions: [
          { type: "cut", path: [{ x: 78, y: 59 }, { x: 97, y: 28 }] },
          { type: "cut", path: [{ x: 96, y: 4 }, { x: 92, y: 30 }] },
        ],
      },
      {
        title: "Entry Pass",
        narrative: "1 enters the ball to 3 on the wing. 2 drops down to fill the weak-side corner.",
        players: [
          { id: "1", label: "1", x: 97, y: 28 },
          { id: "2", label: "2", x: 3, y: 9 },
          { id: "3", label: "3", x: 92, y: 30 },
          { id: "4", label: "4", x: 4, y: 5 },
          { id: "5", label: "5", x: 27, y: 10 },
        ],
        actions: [
          { type: "pass", from: { x: 97, y: 28 }, to: { x: 92, y: 30 } },
          { type: "cut", path: [{ x: 22, y: 62 }, { x: 3, y: 9 }] },
        ],
      },
      {
        title: "Long Cut",
        narrative: "4 makes a long cut from the corner, up the sideline and across the top of the key, as 5 lifts from the block to space the middle.",
        players: [
          { id: "1", label: "1", x: 97, y: 28 },
          { id: "2", label: "2", x: 3, y: 9 },
          { id: "3", label: "3", x: 92, y: 30 },
          { id: "4", label: "4", x: 37, y: 57 },
          { id: "5", label: "5", x: 39, y: 47 },
        ],
        actions: [
          { type: "cut", path: [{ x: 4, y: 5 }, { x: 10, y: 45 }, { x: 37, y: 57 }] },
          { type: "cut", path: [{ x: 27, y: 10 }, { x: 39, y: 47 }] },
        ],
      },
      {
        title: "Reversal",
        narrative: "3 hits 4 in stride at the top of the key as the cut finishes.",
        players: [
          { id: "1", label: "1", x: 97, y: 28 },
          { id: "2", label: "2", x: 3, y: 9 },
          { id: "3", label: "3", x: 92, y: 30 },
          { id: "4", label: "4", x: 37, y: 57 },
          { id: "5", label: "5", x: 39, y: 47 },
        ],
        actions: [
          { type: "pass", from: { x: 92, y: 30 }, to: { x: 37, y: 57 } },
        ],
      },
      {
        title: "Drive & Score",
        narrative: "4 catches in rhythm and attacks downhill for the finish at the rim.",
        players: [
          { id: "1", label: "1", x: 97, y: 28 },
          { id: "2", label: "2", x: 3, y: 9 },
          { id: "3", label: "3", x: 92, y: 30 },
          { id: "4", label: "4", x: 51, y: 9 },
          { id: "5", label: "5", x: 39, y: 47 },
        ],
        actions: [
          { type: "cut", path: [{ x: 37, y: 57 }, { x: 51, y: 9 }] },
        ],
      },
    ],
  },
  {
    id: "4high-motion",
    name: "4-High Motion Continuity",
    category: "Half-Court Offense",
    description: "A repeating read-and-react motion pattern rather than a scripted set play — shown here as one full sequence through the continuity, ending in a rim finish. Use it to teach the spacing and cutting principles, not as a fixed script.",
    keyPoints: [
      "1 passes to 2, then clears through the middle to the opposite side.",
      "3 and 4 loop through the lane, exchanging wing and corner spots as the defense adjusts.",
      "1 continues cutting all the way down to the corner looking for the return pass.",
      "2 finds 1 in the corner; 1 quickly hits 5 sliding into the middle for the downhill score.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 32, y: 59 },
        { id: "2", label: "2", x: 2, y: 43 },
        { id: "3", label: "3", x: 69, y: 60 },
        { id: "4", label: "4", x: 99, y: 45 },
        { id: "5", label: "5", x: 50, y: 47 },
      ],
      actions: [
        { type: "pass", from: { x: 32, y: 59 }, to: { x: 2, y: 43 } },
        { type: "cut", path: [{ x: 32, y: 59 }, { x: 65, y: 46 }, { x: 26, y: 7 }] },
        { type: "cut", path: [{ x: 69, y: 60 }, { x: 77, y: 32 }, { x: 76, y: 59 }] },
        { type: "cut", path: [{ x: 99, y: 45 }, { x: 96, y: 16 }, { x: 62, y: 59 }, { x: 97, y: 32 }] },
        { type: "cut", path: [{ x: 50, y: 47 }, { x: 49, y: 27 }] },
        { type: "pass", from: { x: 2, y: 43 }, to: { x: 26, y: 7 } },
        { type: "pass", from: { x: 26, y: 7 }, to: { x: 49, y: 27 } },
        { type: "cut", path: [{ x: 49, y: 27 }, { x: 49, y: 9 }] },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "Four players spread high above the three-point line with 5 in the middle. 1 has the ball at the top.",
        players: [
          { id: "1", label: "1", x: 32, y: 59 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 69, y: 60 },
          { id: "4", label: "4", x: 99, y: 45 },
          { id: "5", label: "5", x: 50, y: 47 },
        ],
        actions: [],
      },
      {
        title: "Entry Pass & Clear",
        narrative: "1 passes to 2, then cuts through the middle and clears to the right side.",
        players: [
          { id: "1", label: "1", x: 65, y: 46 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 69, y: 60 },
          { id: "4", label: "4", x: 99, y: 45 },
          { id: "5", label: "5", x: 50, y: 47 },
        ],
        actions: [
          { type: "pass", from: { x: 32, y: 59 }, to: { x: 2, y: 43 } },
          { type: "cut", path: [{ x: 32, y: 59 }, { x: 65, y: 46 }] },
        ],
      },
      {
        title: "Perimeter Exchange",
        narrative: "3 and 4 loop through the lane, exchanging wing and corner spots as the defense works to track the cutters.",
        players: [
          { id: "1", label: "1", x: 65, y: 46 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 76, y: 59 },
          { id: "4", label: "4", x: 97, y: 32 },
          { id: "5", label: "5", x: 50, y: 47 },
        ],
        actions: [
          { type: "cut", path: [{ x: 69, y: 60 }, { x: 77, y: 32 }, { x: 76, y: 59 }] },
          { type: "cut", path: [{ x: 99, y: 45 }, { x: 96, y: 16 }, { x: 62, y: 59 }, { x: 97, y: 32 }] },
        ],
      },
      {
        title: "Cut to the Corner",
        narrative: "1 continues cutting all the way down to the left corner, looking for the ball as the defense gets caught in the traffic.",
        players: [
          { id: "1", label: "1", x: 26, y: 7 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 76, y: 59 },
          { id: "4", label: "4", x: 97, y: 32 },
          { id: "5", label: "5", x: 50, y: 47 },
        ],
        actions: [
          { type: "cut", path: [{ x: 65, y: 46 }, { x: 26, y: 7 }] },
        ],
      },
      {
        title: "Slide to the Middle",
        narrative: "5 slides into the middle, ready for a quick catch and go.",
        players: [
          { id: "1", label: "1", x: 26, y: 7 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 76, y: 59 },
          { id: "4", label: "4", x: 97, y: 32 },
          { id: "5", label: "5", x: 49, y: 27 },
        ],
        actions: [
          { type: "cut", path: [{ x: 50, y: 47 }, { x: 49, y: 27 }] },
        ],
      },
      {
        title: "Corner Pass",
        narrative: "2 finds 1 open in the left corner.",
        players: [
          { id: "1", label: "1", x: 26, y: 7 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 76, y: 59 },
          { id: "4", label: "4", x: 97, y: 32 },
          { id: "5", label: "5", x: 49, y: 27 },
        ],
        actions: [
          { type: "pass", from: { x: 2, y: 43 }, to: { x: 26, y: 7 } },
        ],
      },
      {
        title: "Quick Hit & Score",
        narrative: "1 immediately swings it to 5 in the middle, who attacks downhill and finishes at the rim.",
        players: [
          { id: "1", label: "1", x: 26, y: 7 },
          { id: "2", label: "2", x: 2, y: 43 },
          { id: "3", label: "3", x: 76, y: 59 },
          { id: "4", label: "4", x: 97, y: 32 },
          { id: "5", label: "5", x: 49, y: 9 },
        ],
        actions: [
          { type: "pass", from: { x: 26, y: 7 }, to: { x: 49, y: 27 } },
          { type: "cut", path: [{ x: 49, y: 27 }, { x: 49, y: 9 }] },
        ],
      },
    ],
  },
  {
    id: "rot-vs-zone",
    name: "Rot (vs. Zone)",
    category: "Zone Offense",
    description: "Continuity to attack zone defenses from a two-guard set: the ball-side guard enters to the wing and cuts to the low block while the guards rotate up behind, and if the cutter isn't fed, they clear to the weak wing — the whole shape then mirrors and repeats to the other side, on and on.",
    keyPoints: [
      "1 and 2 start in the slots, slightly above the three-point line; 3 and 4 are on the wings, slightly above free-throw line height and outside the three-point line. 2 has the ball.",
      "2 passes to 4 and cuts to the low block. At the same time, 1 fills 2's vacated slot, and 3 fills 1's vacated slot.",
      "If 2 doesn't get the ball at the block, it clears to the far wing, taking over 3's original spot.",
      "4 reverses the ball to 1, who reverses it to 3, who passes to 2 and cuts to the low block the same way 2 did at the start — 1 fills 3's vacated slot, and 4 fills 1's vacated slot.",
      "The pattern now repeats indefinitely, mirroring to the other side each time the ball reverses.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 35, y: 61 },
        { id: "2", label: "2", x: 65, y: 61 },
        { id: "3", label: "3", x: 10, y: 44 },
        { id: "4", label: "4", x: 90, y: 44 },
        { id: "5", label: "5", x: 50, y: 38 },
      ],
      actions: [
        { type: "pass", from: { x: 65, y: 61 }, to: { x: 90, y: 44 } },
        { type: "cut", path: [{ x: 65, y: 61 }, { x: 60, y: 35 }, { x: 68, y: 8 }] },
        { type: "cut", path: [{ x: 35, y: 61 }, { x: 65, y: 61 }] },
        { type: "cut", path: [{ x: 10, y: 44 }, { x: 35, y: 61 }] },
        { type: "cut", path: [{ x: 68, y: 8 }, { x: 35, y: 15 }, { x: 10, y: 44 }] },
        { type: "pass", from: { x: 90, y: 44 }, to: { x: 65, y: 61 } },
        { type: "pass", from: { x: 65, y: 61 }, to: { x: 35, y: 61 } },
        { type: "pass", from: { x: 35, y: 61 }, to: { x: 10, y: 44 } },
        { type: "cut", path: [{ x: 35, y: 61 }, { x: 30, y: 35 }, { x: 32, y: 8 }] },
        { type: "cut", path: [{ x: 65, y: 61 }, { x: 35, y: 61 }] },
        { type: "cut", path: [{ x: 90, y: 44 }, { x: 65, y: 61 }] },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "1 and 2 start in the slots, slightly above the three-point line. 3 and 4 are on the wings, slightly above free-throw line height and outside the three-point line. 2 has the ball. 5 holds the high post.",
        players: [
          { id: "1", label: "1", x: 35, y: 61 },
          { id: "2", label: "2", x: 65, y: 61 },
          { id: "3", label: "3", x: 10, y: 44 },
          { id: "4", label: "4", x: 90, y: 44 },
          { id: "5", label: "5", x: 50, y: 38 },
        ],
        actions: [],
      },
      {
        title: "Entry Pass & Cut",
        narrative: "2 passes to 4 and cuts through the lane to the low block. At the same time, 1 fills 2's vacated slot, and 3 fills 1's vacated slot.",
        players: [
          { id: "1", label: "1", x: 65, y: 61 },
          { id: "2", label: "2", x: 68, y: 8 },
          { id: "3", label: "3", x: 35, y: 61 },
          { id: "4", label: "4", x: 90, y: 44 },
          { id: "5", label: "5", x: 50, y: 38 },
        ],
        actions: [
          { type: "pass", from: { x: 65, y: 61 }, to: { x: 90, y: 44 } },
          { type: "cut", path: [{ x: 65, y: 61 }, { x: 60, y: 35 }, { x: 68, y: 8 }] },
          { type: "cut", path: [{ x: 35, y: 61 }, { x: 65, y: 61 }] },
          { type: "cut", path: [{ x: 10, y: 44 }, { x: 35, y: 61 }] },
        ],
      },
      {
        title: "2 Clears to the Weak Side",
        narrative: "2 doesn't get the ball at the low block, so it clears across to the far wing, taking over the spot 3 started in.",
        players: [
          { id: "1", label: "1", x: 65, y: 61 },
          { id: "2", label: "2", x: 10, y: 44 },
          { id: "3", label: "3", x: 35, y: 61 },
          { id: "4", label: "4", x: 90, y: 44 },
          { id: "5", label: "5", x: 50, y: 38 },
        ],
        actions: [
          { type: "cut", path: [{ x: 68, y: 8 }, { x: 35, y: 15 }, { x: 10, y: 44 }] },
        ],
      },
      {
        title: "Reversal & Mirror Cut",
        narrative: "4 reverses the ball to 1, who reverses it to 3, who passes to 2 and cuts to the low block the same way 2 did at the start. 1 fills 3's vacated slot, and 4 fills 1's vacated slot — the team is now in the same shape as after the first entry, just mirrored. From here the pattern repeats indefinitely, flipping sides with every reversal.",
        players: [
          { id: "1", label: "1", x: 35, y: 61 },
          { id: "2", label: "2", x: 10, y: 44 },
          { id: "3", label: "3", x: 32, y: 8 },
          { id: "4", label: "4", x: 65, y: 61 },
          { id: "5", label: "5", x: 50, y: 38 },
        ],
        actions: [
          { type: "pass", from: { x: 90, y: 44 }, to: { x: 65, y: 61 }, beat: 0 },
          { type: "pass", from: { x: 65, y: 61 }, to: { x: 35, y: 61 }, beat: 1 },
          { type: "pass", from: { x: 35, y: 61 }, to: { x: 10, y: 44 }, beat: 2 },
          { type: "cut", path: [{ x: 35, y: 61 }, { x: 30, y: 35 }, { x: 32, y: 8 }], beat: 2 },
          { type: "cut", path: [{ x: 65, y: 61 }, { x: 35, y: 61 }], beat: 2 },
          { type: "cut", path: [{ x: 90, y: 44 }, { x: 65, y: 61 }], beat: 2 },
        ],
      },
    ],
  },
  {
    id: "split-vs-man",
    name: "Split (vs. Man-to-Man)",
    category: "Man-to-Man Offense",
    description: "Read-heavy continuity built around back-to-back screens from 5 for the split cutters, a guard lift to reset the point, and a staggered screen to spring the shooter — if the first cutter doesn't score, the read just keeps flowing.",
    keyPoints: [
      "1 passes to 3 and cuts in front of 5 to the opposite low block, using 5 as a screen. (Option: 3 can drive if the defense helps off.)",
      "After 1 clears, 2 cuts in front of 5 to the opposite low block the same way, also screened by 5.",
      "After 2 clears, 4 lifts to the top of the key to receive from 3, as 1 lifts to fill 4's original spot.",
      "3 runs to the low block, uses a screen from 2, and continues to the opposite low block. At the same time, 4 reverses the ball back to 1.",
      "5 sets the first screen and 4 sets the one behind him, staggered for 2, who curls up to the top for the catch-and-shoot — or all the way to the rim if the defense chases.",
    ],
    diagram: {
      players: [
        { id: "1", label: "1", x: 66, y: 71 },
        { id: "2", label: "2", x: 34, y: 71 },
        { id: "3", label: "3", x: 90, y: 54 },
        { id: "4", label: "4", x: 10, y: 54 },
        { id: "5", label: "5", x: 50, y: 45 },
      ],
      actions: [
        { type: "pass", from: { x: 66, y: 71 }, to: { x: 90, y: 54 } },
        { type: "cut", path: [{ x: 66, y: 71 }, { x: 50, y: 45 }, { x: 30, y: 8 }] },
        { type: "screen", at: { x: 50, y: 45 }, angle: 0 },
        { type: "cut", path: [{ x: 34, y: 71 }, { x: 50, y: 45 }, { x: 70, y: 8 }] },
        { type: "cut", path: [{ x: 10, y: 54 }, { x: 50, y: 64 }] },
        { type: "pass", from: { x: 90, y: 54 }, to: { x: 50, y: 64 } },
        { type: "cut", path: [{ x: 30, y: 8 }, { x: 15, y: 40 }, { x: 10, y: 54 }] },
        { type: "cut", path: [{ x: 90, y: 54 }, { x: 70, y: 15 }, { x: 30, y: 8 }] },
        { type: "screen", at: { x: 70, y: 8 }, angle: 90 },
        { type: "pass", from: { x: 50, y: 64 }, to: { x: 10, y: 54 } },
        { type: "cut", path: [{ x: 50, y: 64 }, { x: 55, y: 35 }] },
        { type: "cut", path: [{ x: 50, y: 45 }, { x: 60, y: 25 }] },
        { type: "screen", at: { x: 60, y: 25 }, angle: 0 },
        { type: "screen", at: { x: 55, y: 35 }, angle: 0 },
        { type: "cut", path: [{ x: 70, y: 8 }, { x: 68, y: 22 }, { x: 63, y: 38 }, { x: 50, y: 55 }] },
        { type: "pass", from: { x: 10, y: 54 }, to: { x: 50, y: 55 } },
      ],
    },
    steps: [
      {
        title: "Initial Alignment",
        narrative: "1 and 2 start outside the three-point line, at the extension of the sides of the box. 3 and 4 are on the wings, slightly above the extension of the free-throw line and outside the three-point line. 5 holds the high post. 1 has the ball.",
        players: [
          { id: "1", label: "1", x: 66, y: 71 },
          { id: "2", label: "2", x: 34, y: 71 },
          { id: "3", label: "3", x: 90, y: 54 },
          { id: "4", label: "4", x: 10, y: 54 },
          { id: "5", label: "5", x: 50, y: 45 },
        ],
        actions: [],
      },
      {
        title: "1 Cuts Off 5's Screen",
        narrative: "1 passes to 3 and cuts in front of 5 to the opposite low block, using 5 as a screen. This also opens a driving lane for 3 if the defense helps off to cover the cutter.",
        players: [
          { id: "1", label: "1", x: 30, y: 8 },
          { id: "2", label: "2", x: 34, y: 71 },
          { id: "3", label: "3", x: 90, y: 54 },
          { id: "4", label: "4", x: 10, y: 54 },
          { id: "5", label: "5", x: 50, y: 45 },
        ],
        actions: [
          { type: "pass", from: { x: 66, y: 71 }, to: { x: 90, y: 54 } },
          { type: "cut", path: [{ x: 66, y: 71 }, { x: 50, y: 45 }, { x: 30, y: 8 }] },
          { type: "screen", at: { x: 50, y: 45 }, angle: 0 },
        ],
      },
      {
        title: "2 Cuts Off 5's Screen",
        narrative: "After 1 clears the middle, 2 cuts in front of 5 to the opposite low block the same way, also screened by 5.",
        players: [
          { id: "1", label: "1", x: 30, y: 8 },
          { id: "2", label: "2", x: 70, y: 8 },
          { id: "3", label: "3", x: 90, y: 54 },
          { id: "4", label: "4", x: 10, y: 54 },
          { id: "5", label: "5", x: 50, y: 45 },
        ],
        actions: [
          { type: "cut", path: [{ x: 34, y: 71 }, { x: 50, y: 45 }, { x: 70, y: 8 }] },
          { type: "screen", at: { x: 50, y: 45 }, angle: 0 },
        ],
      },
      {
        title: "4 Lifts, 1 Fills",
        narrative: "After 2 clears, 4 lifts to the top of the key and receives the ball from 3. At the same time, 1 lifts from the block to fill 4's original spot.",
        players: [
          { id: "1", label: "1", x: 10, y: 54 },
          { id: "2", label: "2", x: 70, y: 8 },
          { id: "3", label: "3", x: 90, y: 54 },
          { id: "4", label: "4", x: 50, y: 64 },
          { id: "5", label: "5", x: 50, y: 45 },
        ],
        actions: [
          { type: "cut", path: [{ x: 10, y: 54 }, { x: 50, y: 64 }] },
          { type: "pass", from: { x: 90, y: 54 }, to: { x: 50, y: 64 } },
          { type: "cut", path: [{ x: 30, y: 8 }, { x: 15, y: 40 }, { x: 10, y: 54 }] },
        ],
      },
      {
        title: "3 Cuts Off 2's Screen, Ball Reverses",
        narrative: "3 runs to the low block, uses a screen from 2, and continues to the opposite low block. At the same time, 4 reverses the ball back to 1.",
        players: [
          { id: "1", label: "1", x: 10, y: 54 },
          { id: "2", label: "2", x: 70, y: 8 },
          { id: "3", label: "3", x: 30, y: 8 },
          { id: "4", label: "4", x: 50, y: 64 },
          { id: "5", label: "5", x: 50, y: 45 },
        ],
        actions: [
          { type: "cut", path: [{ x: 90, y: 54 }, { x: 70, y: 15 }, { x: 30, y: 8 }] },
          { type: "screen", at: { x: 70, y: 8 }, angle: 90 },
          { type: "pass", from: { x: 50, y: 64 }, to: { x: 10, y: 54 } },
        ],
      },
      {
        title: "Staggered Screen",
        narrative: "5 sets the first screen and 4 sets the one behind him, staggered for 2, who curls up to the top for the catch-and-shoot — or all the way to the rim if the defense chases over the top.",
        players: [
          { id: "1", label: "1", x: 10, y: 54 },
          { id: "2", label: "2", x: 50, y: 55 },
          { id: "3", label: "3", x: 30, y: 8 },
          { id: "4", label: "4", x: 55, y: 35 },
          { id: "5", label: "5", x: 60, y: 25 },
        ],
        actions: [
          { type: "cut", path: [{ x: 50, y: 64 }, { x: 55, y: 35 }] },
          { type: "cut", path: [{ x: 50, y: 45 }, { x: 60, y: 25 }] },
          { type: "screen", at: { x: 60, y: 25 }, angle: 0 },
          { type: "screen", at: { x: 55, y: 35 }, angle: 0 },
          { type: "cut", path: [{ x: 70, y: 8 }, { x: 68, y: 22 }, { x: 63, y: 38 }, { x: 50, y: 55 }] },
          { type: "pass", from: { x: 10, y: 54 }, to: { x: 50, y: 55 } },
        ],
      },
    ],
  },
];
